### PR TITLE
Increase allowed version of peer dep

### PR DESCRIPTION
**Pull request by willfarrell**
rollup is now at v2. From some quick testing, this package works just fine with it.

### CODE REVIEW

**Comment by TrySound** [comment]
Hi, thanks for heads up. Could you please upgrade rollup in dev dependencies? This will let CI to check this too.

**Comment by willfarrell** [comment]
Sorry, I missed it. Version updated.

**Comment by TrySound** [comment]
Run yarn and commit lockfile please

**Comment by willfarrell** [comment]
lol, What a start to the week. So sorry. I was doing everything in the browser. It should be good now. I hope.

**Comment by TrySound** [comment]
New rollup does not work in old node. We do not drop old rollup support but we can just stop testing in old node. Tweak .travis.yml please.

**Comment by willfarrell** [comment]
I was about to ask if you'd like me to do that. Done.

**Comment by TrySound** [comment]
But add 10 and 12 please

**Comment by willfarrell** [comment]
You got it.

**Comment by TrySound** [comment]
Thanks!

**Pull request merged**
